# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: VoiceFilterService.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'VoiceFilterService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18VoiceFilterService.proto\x12\x0cjsk.services\"\x1d\n\x0c\x45mbedRequest\x12\r\n\x05\x41udio\x18\x01 \x01(\x0c\"\"\n\rEmbedResponse\x12\x11\n\tEmbedding\x18\x01 \x03(\x02\"1\n\rFilterRequest\x12\r\n\x05\x41udio\x18\x01 \x01(\x0c\x12\x11\n\tEmbedding\x18\x02 \x03(\x02\"\x1f\n\x0e\x46ilterResponse\x12\r\n\x05\x41udio\x18\x01 \x01(\x0c\x32\x9b\x01\n\x12VoiceFilterService\x12@\n\x05\x45mbed\x12\x1a.jsk.services.EmbedRequest\x1a\x1b.jsk.services.EmbedResponse\x12\x43\n\x06\x46ilter\x12\x1b.jsk.services.FilterRequest\x1a\x1c.jsk.services.FilterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'VoiceFilterService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=42
  _globals['_EMBEDREQUEST']._serialized_end=71
  _globals['_EMBEDRESPONSE']._serialized_start=73
  _globals['_EMBEDRESPONSE']._serialized_end=107
  _globals['_FILTERREQUEST']._serialized_start=109
  _globals['_FILTERREQUEST']._serialized_end=158
  _globals['_FILTERRESPONSE']._serialized_start=160
  _globals['_FILTERRESPONSE']._serialized_end=191
  _globals['_VOICEFILTERSERVICE']._serialized_start=194
  _globals['_VOICEFILTERSERVICE']._serialized_end=349
# @@protoc_insertion_point(module_scope)
